Created Prisma Schema and Postgres DB
nola-civic-hacking/fridge-friend pull request #5
Opened 2023-06-12 16:38 UTC by eekbk

2023-06-12 23:50 UTC, wilsuriel03 requested changes

2023-06-12 23:50 UTC, wilsuriel03 commented on schema.prisma
Hi Eric,

I've been reviewing the Prisma schema and wanted to suggest a few improvements and ask some clarifying questions.

**User model:** We have both openedTickets and claimedTickets relations with the Ticket model. These are well defined. However, there's also a tickets field which is not associated with any relation. Can you clarify what the purpose of this field is? If it is redundant, I suggest we remove it.

**Fridge model:** Similar to the User model, we have tickets and users fields without any relations. It would be helpful to clearly define what these relations represent, or consider removing them if they're not needed.

**Fridge model:** There is a mainImageId field, but it doesn't seem to be related to any Image model. If the intention is to reference an image, I suggest we define it as a relation to the FridgeImages or Image model.

**UserProfileImages and FridgeImages:** If these are meant to be types of Image, it might be cleaner to consolidate them into one model and use an enum field to distinguish between them. We could then use a relation to link each User or Fridge to their associated Images. What do you think about this approach?

**UserProfileImages and FridgeImages:** Both have a isCurrent Boolean field. If it's intended to show the currently displayed image, we should consider using a nullable relation field in the User and Fridge models. This will allow us to ensure that there's only one current image per User or Fridge at any given time.

Please let me know your thoughts on these suggestions.

2023-06-13 03:32 UTC, eekbk commented on schema.prisma
Hey Wilbur,

Thanks for the thorough feedback. 

I made some changes, based on your suggestions.  For others, I made some comments in the code to clarify the purpose of the field. If they are still unclear or if you still have thoughts about them, I can discuss over Zoom or Slack.

User model: I updated the "tickets" field to "closedTickets" and put the corresponding relation on it and the Tickets model. Also got rid of "fridges" field. That is covered by "subscriptions" field

Fridge model: removed "users" field and "openTickets" boolean. I was trying to cut down on queries with that Boolean, but actually I think it won't affect query count that much, if at all.

Let me know what you think and I can chat over Zoom or Slack if it's helpful

2023-06-13 04:05 UTC, wilsuriel03 requested changes

2023-06-13 04:05 UTC, wilsuriel03 commented on schema.prisma
Thank you for taking the time to address the suggestions I made previously and providing clarifications. The schema is definitely clearer. However, there are a couple of points that I believe could benefit from further discussion or clarification liek: 

**Fridge model and Image model:** The mainImageId field in the Fridge model is still unlinked to any of the Image models. My understanding is that this field is meant to reference a specific image, presumably the main image for the fridge? Currently, it is unclear which image this field refers to. Would it make sense to represent this as a relation to the Image model to provide more clarity?

**UserProfileImages and FridgeImages:** The purpose of the isCurrent field is now more clear to me, thanks for the explanation. However, one concern that still stands is the potential for data inconsistencies. As it is right now, there's nothing preventing multiple images from being marked as 'current' for the same user or fridge. Even tho this could be handled in the application logic, I believe it could be beneficial to discuss this further to explore other possible solutions.

2023-06-13 04:05 UTC, wilsuriel03 commented on schema.prisma
Imagine you have a User who has uploaded different profile images over time. To keep track of the current profile picture, we use the "isCurrent" field. Let's say the User has three images with IDs "img1," "img2," and "img3," and all of them are marked as current. This creates a problem because we don't know which image is actually the current profile picture. As a result, the application may show the wrong picture as the profile image.

The same issue can occur with the Fridge model. If multiple images of a fridge are marked as current, it's unclear which image should be displayed as the main picture for that fridge. If that makes sensee🤔

2023-07-03 17:51 UTC, eekbk commented
Hi Wilber,

Thanks for the notes. I just returned from vacation and want to get this PR merged. 

Let me know over Slack or Discord when you are available to do quick virtual meetup to discuss the schema. 

Thanks

2023-07-14 20:17 UTC, wilsuriel03 approved these changes
Well done eric, I will go ahead and merge to main

2023-07-14 22:51 UTC, itcomesinwaves approved these changes
Nice!

2023-07-14 22:51 UTC, merged